name: runing sender

on:

  push:

    branches: [ master ]

  pull_request:

    branches: [ master ]

jobs:

  build:

    runs-on: windows-2019

    steps:

    - uses: actions/checkout@v2
    
    - name : run sender.exe
      run : .\MC3File\imgt.exe MERGE_STORE_SCP 1 2
    
    - name: move gcno to sender test dir
      run: move *.gcno SenderTest 

    - name: move senderTestApp to mc3lib
      run: move senderTestApp.exe mc3lib
    
    - name: cd into mc3lib to run sender
      run: cd mc3lib && ./senderTestApp.exe 

    - name: move .gcda files to sender test dir
      run:  move *.gcda SenderTest

    - name: sender coverage report
      run:  gcov -r SenderTest\*.cpp
