name: runing sender

on:

  push:

    branches: [ master ]

  pull_request:

    branches: [ master ]

jobs:
  build-project:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2 
      with:
          vs-version: 15.0
    
    - name: subscribe1 build
      run: msbuild scu.vcxproj /p:configuration=debug /p:platform=x64
    
    - name: copy scu.exe to .\MC3File
      run : copy .\x64\Debug\scu.exe  .\MC3File\
    
    - name: run scu
      run : .\MC3File\scu.exe MERGE_STORE_SCP 1 2
 
  build-receiver:
    
    runs-on: windows-2019
    
    steps:
  
    - uses: actions/checkout@v2
      
    - name : run stor_scp.exe
      run : .\Receiver\stor_scp.exe
      
    - name: build senderTestApplication
      run: g++ -S SenderTest\ImageListTest.cpp --coverage
    
    - name: move gcno to sender test dir
      run: move *.gcno SenderTest 

    - name: move senderTestApp to mc3lib
      run: move senderTestApp.exe mc3lib
    
    - name: cd into mc3lib to run sender
      run: cd mc3lib && ./senderTestApp.exe 

    - name: move .gcda files to sender test dir
      run:  move *.gcda SenderTest

    - name: sender coverage report
      run:  gcov -r SenderTest\*.cpp
