name: Python unit testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python # Set Python version
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      # Install pip and pytest
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install paho-mqtt
          pip install --upgrade pyflakes
      - name: Test with pytest
        run: |
          pytest ./DiagnosisStatusUpdateTest/subscribeDiagonisedimageNameAndUpdateStatus_test.py
          pytest ./TestingCsvCreationAndWriting/SubcribeImageNameAndWriteIntoCsv_test.py
 
      - name: check python files
        run :  pyflakes  ./DiagonosisStatus/subscribeDiagonisedImageNameAndUpdateStatus.py
     
